import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Topnav";
import AISidebar from "@/components/AISidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AlIce Advising Tool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 antialiased`}
      >
        <div className="h-screen grid grid-cols-[70%_30%] w-full grid-rows-[64px_auto]">
          <div className="fixed z-10 w-full row-start-1 col-start-1 col-span-2"><Navbar /></div>
          <div className="row-start-2 col-start-1 overflow-y-auto">{children}</div>
          {/* AI Sidebar */}
          <aside className="border-l border-gray-200 bg-white row-start-2 col-start-2 overflow-y-auto">
            <AISidebar />
          </aside>
        </div>
      </body>
    </html>
  );
}
